// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA115xtxBEwiDjsuh-URniKDNg2rtW6m4Y',
    appId: '1:847587799178:web:9e809e05b216a9c93a3d73',
    messagingSenderId: '847587799178',
    projectId: 'job-service-mob-app',
    authDomain: 'job-service-mob-app.firebaseapp.com',
    storageBucket: 'job-service-mob-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJnp2Z0AAcQV9PcZCeSzDrgcfFZhZ0AUA',
    appId: '1:847587799178:android:9a4dd48d0fee985e3a3d73',
    messagingSenderId: '847587799178',
    projectId: 'job-service-mob-app',
    storageBucket: 'job-service-mob-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdzcU2DGvZjnl8Az0mKG29SouYZdiyIvE',
    appId: '1:847587799178:ios:41f95de9fc955aa83a3d73',
    messagingSenderId: '847587799178',
    projectId: 'job-service-mob-app',
    storageBucket: 'job-service-mob-app.appspot.com',
    iosClientId: '847587799178-56l7qmqvfq62hkjd8mq0hnebbrhnpd24.apps.googleusercontent.com',
    iosBundleId: 'com.jobserviceapp.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdzcU2DGvZjnl8Az0mKG29SouYZdiyIvE',
    appId: '1:847587799178:ios:f2a91b2f5f86a35d3a3d73',
    messagingSenderId: '847587799178',
    projectId: 'job-service-mob-app',
    storageBucket: 'job-service-mob-app.appspot.com',
    iosClientId: '847587799178-q3t90kpcgveohqjo97evifmq7k3ejr1e.apps.googleusercontent.com',
    iosBundleId: 'com.jobserviceapp.jobServiceApp.RunnerTests',
  );
}
