// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDT6S6OaeEMe54zaiNaYLophpS_sEoGlK8',
    appId: '1:1096590455640:web:73621020805af833e3eb2d',
    messagingSenderId: '1096590455640',
    projectId: 'job-portal-app-fc91a',
    authDomain: 'job-portal-app-fc91a.firebaseapp.com',
    storageBucket: 'job-portal-app-fc91a.appspot.com',
    measurementId: 'G-M49FWF4M1M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4ZTVtOmgepj1n9VrVURmuPNLTDpEZb3Y',
    appId: '1:1096590455640:android:5e520a2b9ca70097e3eb2d',
    messagingSenderId: '1096590455640',
    projectId: 'job-portal-app-fc91a',
    storageBucket: 'job-portal-app-fc91a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2vi1QOTBEdfyGtgmIS3TRxPhrq9s_R9E',
    appId: '1:1096590455640:ios:c8121b589261ad79e3eb2d',
    messagingSenderId: '1096590455640',
    projectId: 'job-portal-app-fc91a',
    storageBucket: 'job-portal-app-fc91a.appspot.com',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2vi1QOTBEdfyGtgmIS3TRxPhrq9s_R9E',
    appId: '1:1096590455640:ios:58a8e6a427429250e3eb2d',
    messagingSenderId: '1096590455640',
    projectId: 'job-portal-app-fc91a',
    storageBucket: 'job-portal-app-fc91a.appspot.com',
    iosBundleId: 'com.example.foodDeliveryApp.RunnerTests',
  );
}
